version: '3.8'

services:
  nextjs:
    build:
      context: ./learn-fabric-js-next
      dockerfile: Dockerfile
    container_name: nextjs-app
    expose:
      - 3000
    environment:
      - NODE_ENV=production
      - PORT=3000

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextjs
